[build]
builder = "nixpacks"
buildCommand = "npx prisma db push --accept-data-loss --skip-generate && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
