#!/usr/bin/env node
// _build_es_tools.mjs — assemble Spanish counterparts for the 12 interactive tools + the
// tools hub from scripts/.es-tools.json. The calculator <script> is NOT regenerated by the
// model: each user-facing string literal is substituted INSIDE the original English script's
// string literals only (code, ids, math, and event names are never touched), so the JS is
// provably logic-identical and duplicated strings (e.g. a CATS name that doubles as a STEPS
// key) auto-sync. Emits a strict integrity report; injects hreflang into the EN originals.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const RES = fileURLToPath(new URL('../public/resources/', import.meta.url));
const TOOLS_DIR = join(RES, 'tools');
const DATA = JSON.parse(readFileSync(fileURLToPath(new URL('./.es-tools.json', import.meta.url)), 'utf8')).result;
const ORIGIN = 'https://goodcircles.org';
const FONTS = 'https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800;900&family=Fira+Sans:wght@400;500;600;700&display=swap';
const TOOL_SLUGS = ['attribution-vs-contribution-aid','board-composition-matrix','donor-retention-ltv-calculator','functional-expense-allocator','gift-range-chart-generator','grant-readiness-assessment','indirect-cost-calculator','lobbying-limit-501h-calculator','operating-reserve-calculator','passive-funding-calculator','public-support-test-calculator','wcag-accessibility-quick-audit'];

const ENT = (s) => String(s == null ? '' : s)
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')
  .replace(/&#0?39;/g, "'").replace(/&#x27;/gi, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&');
const escAttr = (s) => ENT(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const escText = (s) => ENT(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const stripTags = (s) => ENT(s).replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const jsonld = (o) => JSON.stringify(o).replace(/</g, '\\u003c');

// Corrections for literals the model listed incorrectly (e.g. it baked in an interpolated value).
const SUPPLEMENT = {
  'grant-readiness-assessment': [{ en: ' of 12 answered', es: ' de 12 respondidas' }],
};
const htmlAmp = (s) => s.replace(/&/g, '&amp;'); // innerHTML literals keep raw tags but encode &

// Split JS into ordered code / string-literal segments. Only string literals get translated.
function tokenize(code) {
  const segs = []; let i = 0, last = 0; const n = code.length;
  const pushCode = (a, b) => { if (b > a) segs.push({ type: 'code', text: code.slice(a, b) }); };
  while (i < n) {
    const c = code[i];
    if (c === '"' || c === "'" || c === '`') {
      pushCode(last, i); const q = c; const start = i; i++;
      while (i < n) { if (code[i] === '\\') { i += 2; continue; } if (code[i] === q) { i++; break; } i++; }
      segs.push({ type: 'str', text: code.slice(start, i) }); last = i;
    } else if (c === '/' && code[i + 1] === '/') { while (i < n && code[i] !== '\n') i++; }
    else if (c === '/' && code[i + 1] === '*') { i += 2; while (i < n && !(code[i] === '*' && code[i + 1] === '/')) i++; i += 2; }
    else i++;
  }
  pushCode(last, n);
  return segs;
}

// Substitute user-facing literals inside string literals only.
function buildEsScript(enScript, pairs, slug, report) {
  const norm = [...(pairs || []), ...(SUPPLEMENT[slug] || [])]
    .map((p) => ({ en: ENT(p.en), es: ENT(p.es) }))
    .filter((p) => p.en.trim().length >= 2 && /[A-Za-zÀ-ÿ]/.test(p.en)); // drop '$', whitespace-only, etc.
  const seen = new Set(); const uniq = [];
  for (const p of norm) { if (!seen.has(p.en)) { seen.add(p.en); uniq.push(p); } }
  uniq.sort((a, b) => b.en.length - a.en.length); // longest-first: avoid nested-substring clobber

  const esc = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // A single alphanumeric token (e.g. "gap", "Yes") must match only at word boundaries, so it
  // can't corrupt an id/class token that contains it (e.g. the literal 'bm-gaps'). Multi-word /
  // punctuated strings use plain substring matching.
  const sub = (t, find, sent) => {
    if (/^[A-Za-z0-9]+$/.test(find)) {
      const re = new RegExp('\\b' + esc(find) + '\\b', 'g');
      return re.test(t) ? t.replace(new RegExp('\\b' + esc(find) + '\\b', 'g'), sent) : null;
    }
    return t.includes(find) ? t.split(find).join(sent) : null;
  };
  const found = new Set();
  const out = tokenize(enScript).map((seg) => {
    if (seg.type !== 'str') return seg.text;          // CODE: never touched
    let t = seg.text; const repl = [];
    uniq.forEach((p, i) => {
      const sent = '\x00' + i + '\x00';
      let r = sub(t, p.en, sent);
      if (r !== null) { t = r; repl[i] = p.es; found.add(p.en); return; }
      if (p.en.includes('&')) { r = sub(t, htmlAmp(p.en), sent); if (r !== null) { t = r; repl[i] = htmlAmp(p.es); found.add(p.en); } }
    });
    repl.forEach((es, i) => { if (es !== undefined) t = t.split('\x00' + i + '\x00').join(es); });
    return t;
  });
  const s = out.join('');

  for (const p of uniq) if (!found.has(p.en)) report.notFound.push({ slug, en: p.en });
  try { new Function(s); } catch (e) { report.syntax.push({ slug, error: String(e.message) }); }
  // Soft check: flag string literals left identical to English prose (likely untranslated).
  const enLits = tokenize(enScript).filter((x) => x.type === 'str').map((x) => x.text);
  const esLits = tokenize(s).filter((x) => x.type === 'str').map((x) => x.text);
  for (const lit of esLits) {
    const inner = lit.slice(1, -1);
    if (enLits.includes(lit) && /[A-Za-z]{4,}\s+[A-Za-z]{3,}/.test(inner) && !/^[\s\w./#:&;-]+$/.test(inner) === false) {
      if (/\b(the|you|your|and|with|of|to|for|score|answer|grant|reserve|cost|months?)\b/i.test(inner)) report.maybeEnglish.push({ slug, lit: inner.slice(0, 70) });
    }
  }
  return s;
}

// Pull the three JSON-LD objects + the bare calculator <script> + the <style> from an EN page.
function dissect(html) {
  const ld = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map((m) => JSON.parse(m[1]));
  const script = (html.match(/<script>([\s\S]*?)<\/script>/) || [])[1] || '';
  const style = (html.match(/<style>[\s\S]*?<\/style>/) || [])[0] || '';
  return { ld, script, style };
}
const idsBoundBy = (script) => {
  const set = new Set();
  for (const m of script.matchAll(/(?:getElementById|\$)\(\s*['"]([A-Za-z0-9_-]+)['"]\s*\)/g)) set.add(m[1]);
  return set;
};
const inputDefaults = (html) => {
  const map = {};
  for (const m of html.matchAll(/<input\b[^>]*\bid="([^"]+)"[^>]*>/g)) {
    const v = (m[0].match(/\bvalue="([^"]*)"/) || [])[1];
    if (v !== undefined) map[m[1]] = v;
  }
  return map;
};

const NAV = (enUrl) => `<nav class="nav"><div class="wrap"><a class="brand" href="/resources/"><img src="/brand/gc-main-white.svg" alt="Good Circles"></a><div class="links"><a href="/resources/">Recursos</a><a href="/resources/tools/es/">Herramientas</a><a href="/resources/templates/">Plantillas</a><a href="${enUrl}">English</a><a class="btn btn-gold" href="https://goodcircles.org/for-nonprofits" style="padding:9px 16px">Para organizaciones</a></div></div></nav>`;
const FOOTER = `<footer><div class="wrap">
  <div class="ftag">Ahorra. Dona. Apoya lo local.</div>
  <div class="fnav"><a href="/resources/">Recursos</a> · <a href="/resources/tools/es/">Herramientas</a> · <a href="https://goodcircles.org/for-nonprofits">Para organizaciones</a> · <a href="https://goodcircles.org">goodcircles.org</a></div>
  <p class="muted">goodcircles.org · El mercado comunitario · Lanzamiento en septiembre de 2026</p>
</div></footer>`;

const report = { notFound: [], syntax: [], idMismatch: [], valueMismatch: [], maybeEnglish: [], built: 0, hreflang: 0 };
const esNames = {}; // slug -> Spanish h1 (for the hub ItemList)

function bodyToRaw(body) {
  const rawTags = (body.match(/<(div|p|a|ul|ol|table|tr|td|style|input|button|h2|h3|h4|span|form|label)\b/g) || []).length;
  return (rawTags < 3 && body.includes('&lt;')) ? ENT(body) : body;
}
function upgradeEsLinks(articleHtml) {
  return articleHtml.replace(/href="(\/resources\/[^"#?]*?\/)"/g, (m, href) => {
    if (/\/es\/$/.test(href)) return m;
    const rel = href.replace(/^\/resources\//, '').replace(/\/$/, '');
    return existsSync(join(RES, rel, 'es', 'index.html')) ? `href="/resources/${rel}/es/"` : m;
  });
}

for (const { slug, content: c } of DATA) {
  const isHub = !slug;
  const enFile = isHub ? join(TOOLS_DIR, 'index.html') : join(TOOLS_DIR, slug, 'index.html');
  const enHtml = readFileSync(enFile, 'utf8');
  const { ld, script: enScript, style: enStyle } = dissect(enHtml);
  const enUrl = isHub ? `${ORIGIN}/resources/tools/` : `${ORIGIN}/resources/tools/${slug}/`;
  const esUrl = enUrl + 'es/';
  if (!isHub) esNames[slug] = stripTags(c.h1);

  // ---- body ----
  let body = bodyToRaw(c.bodyHtml);
  if (enStyle) {
    if (/<style>[\s\S]*?<\/style>/.test(body)) body = body.replace(/<style>[\s\S]*?<\/style>/, () => enStyle);
    else body = body.replace('</div>\n', '</div>\n' + enStyle + '\n');
  }
  body = upgradeEsLinks(body);
  if (isHub) for (const ts of TOOL_SLUGS) body = body.split(`/resources/tools/${ts}/"`).join(`/resources/tools/${ts}/es/"`);
  // Normalize the "Fuentes y herramientas" verified-date line to the exact form the citation gate accepts.
  const lv = (enHtml.match(/Last verified (\d{4}-\d{2}-\d{2})/) || [])[1];
  if (lv && /Fuentes y herramientas/.test(body)) {
    body = body.replace(/(<p class="muted"[^>]*>)[^<]*?(?:Verificad|Última verificaci|Last verified)[^<]*?(<\/p>)/i,
      `$1Verificado por última vez ${lv}. Las cifras y normas cambian — verifica en la fuente antes de actuar.$2`);
  }

  // ---- calculator script (provably logic-identical) ----
  const esScript = (!isHub && enScript) ? buildEsScript(enScript, c.jsStrings, slug, report) : '';

  // ---- integrity: bound ids + input defaults ----
  if (!isHub && enScript) {
    for (const id of idsBoundBy(enScript)) if (!new RegExp(`id="${id}"`).test(body)) report.idMismatch.push({ slug, id });
    const enDef = inputDefaults(enHtml), esDef = inputDefaults(body);
    for (const id of Object.keys(enDef)) if (esDef[id] !== enDef[id]) report.valueMismatch.push({ slug, id, en: enDef[id], es: esDef[id] });
  }

  // ---- JSON-LD ----
  const ldOut = [];
  const primary = ld.find((x) => x['@type'] === 'WebApplication' || x['@type'] === 'CollectionPage');
  if (primary) ldOut.push({ ...primary, name: stripTags(c.webAppName), description: stripTags(c.webAppDescription), url: esUrl, inLanguage: 'es' });
  if (isHub) {
    ldOut.push({ '@context': 'https://schema.org', '@type': 'ItemList', inLanguage: 'es',
      itemListElement: TOOL_SLUGS.map((ts, i) => ({ '@type': 'ListItem', position: i + 1, name: esNames[ts] || ts, url: `${ORIGIN}/resources/tools/${ts}/es/` })) });
  } else {
    ldOut.push({ '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: 'es',
      mainEntity: (c.faqs || []).map((f) => ({ '@type': 'Question', name: stripTags(f.q), acceptedAnswer: { '@type': 'Answer', text: stripTags(f.a) } })) });
  }
  const crumb = isHub
    ? [['Good Circles', ORIGIN], ['Recursos', `${ORIGIN}/resources/`], ['Herramientas', esUrl]]
    : [['Good Circles', ORIGIN], ['Recursos', `${ORIGIN}/resources/`], ['Herramientas', `${ORIGIN}/resources/tools/`], [stripTags(c.crumbLeaf), esUrl]];
  ldOut.push({ '@context': 'https://schema.org', '@type': 'BreadcrumbList',
    itemListElement: crumb.map(([name, item], i) => ({ '@type': 'ListItem', position: i + 1, name, item })) });

  const crumbHtml = isHub
    ? `<a href="/resources/">Recursos</a> › Herramientas`
    : `<a href="/resources/">Recursos</a> › <a href="/resources/tools/es/">Herramientas</a> › ${escText(c.crumbLeaf)}`;

  const html = `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escText(c.title)}</title>
<meta name="description" content="${escAttr(c.metaDescription)}">
<link rel="canonical" href="${esUrl}">
<link rel="alternate" hreflang="en" href="${enUrl}">
<link rel="alternate" hreflang="es" href="${esUrl}">
<link rel="alternate" hreflang="x-default" href="${enUrl}">
<meta property="og:title" content="${escAttr(c.title)}">
<meta property="og:description" content="${escAttr(c.ogDescription)}">
<meta property="og:locale" content="es_ES">
<meta property="og:type" content="website"><meta property="og:url" content="${esUrl}"><meta property="og:image" content="${ORIGIN}/resources/og.png">
<meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#7851A9">
<link href="${FONTS}" rel="stylesheet">
<link rel="stylesheet" href="/resources/resources.css">
<script type="application/ld+json">${jsonld(ldOut[0])}</script>
<script type="application/ld+json">${jsonld(ldOut[1])}</script>
<script type="application/ld+json">${jsonld(ldOut[2])}</script>
</head><body>
${NAV(enUrl)}
<div class="wrap"><header class="hero">
  <div class="crumb">${crumbHtml}</div>
  <div class="eyebrow">${escText(c.eyebrow)}</div>
  <h1>${escText(c.h1)}</h1>
  <div class="dateline">${escText(c.datelineText)} · <a href="${enUrl}">Read in English</a></div>
</header>
<article>
${body}
</article></div>
${FOOTER}
${esScript ? `<script>${esScript}</script>\n` : ''}<script src="/resources/share.js"></script>
</body></html>
`;

  const outDir = isHub ? join(TOOLS_DIR, 'es') : join(TOOLS_DIR, slug, 'es');
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'index.html'), html, 'utf8');
  report.built++;

  if (!/hreflang="es"/.test(enHtml)) {
    const canon = `<link rel="canonical" href="${enUrl}">`;
    if (enHtml.includes(canon)) {
      writeFileSync(enFile, enHtml.replace(canon, `${canon}\n<link rel="alternate" hreflang="en" href="${enUrl}">\n<link rel="alternate" hreflang="es" href="${esUrl}">\n<link rel="alternate" hreflang="x-default" href="${enUrl}">`), 'utf8');
      report.hreflang++;
    } else report.notFound.push({ slug, en: '[canonical not found in EN page]' });
  }
}

console.log(`es-tools: built ${report.built} pages, hreflang into ${report.hreflang} EN pages`);
const fail = (label, arr) => { if (arr.length) { console.log(`\n!! ${label} (${arr.length}):`); for (const x of arr) console.log('   ', JSON.stringify(x)); } };
fail('jsStrings NOT FOUND in EN script', report.notFound);
fail('ES script SYNTAX errors', report.syntax);
fail('bound id MISSING from ES body', report.idMismatch);
fail('input default VALUE changed', report.valueMismatch);
fail('string literal maybe still English — REVIEW', report.maybeEnglish);
if (!report.notFound.length && !report.syntax.length && !report.idMismatch.length && !report.valueMismatch.length)
  console.log('\n✓ hard integrity checks passed' + (report.maybeEnglish.length ? ` (${report.maybeEnglish.length} soft review items)` : ''));
