import { createHash } from 'crypto';
import { prisma } from '../lib/prisma';

type ContractInput = {
  campaignId: string;
  campaignName: string;
  nonprofitName: string;
  nonprofitEin: string;
  states: string[];
  startDate: Date;
  endDate: Date | null;
  donationMechanism: string;
  donationAmount: number | null;
  donationPercentage: number | null;
  transferDeadlineDays: number;
};

function generateContractText(input: ContractInput): string {
  const today = new Date().toISOString().split('T')[0];
  const endDateStr = input.endDate
    ? input.endDate.toISOString().split('T')[0]
    : 'Open-ended (to be amended)';
  const transferDue = input.endDate
    ? new Date(input.endDate.getTime() + input.transferDeadlineDays * 86400000)
        .toISOString().split('T')[0]
    : `${input.transferDeadlineDays} days after campaign end`;

  const donationDesc =
    input.donationMechanism === 'PER_UNIT'
      ? `$${input.donationAmount?.toFixed(2)} per unit sold`
      : input.donationMechanism === 'FLAT'
      ? `$${input.donationAmount?.toFixed(2)} flat per transaction`
      : `${((input.donationPercentage ?? 0) * 100).toFixed(2)}% of gross sales`;

  return `COMMERCIAL CO-VENTURER AGREEMENT

Date: ${today}
Campaign: ${input.campaignName}
Campaign ID: ${input.campaignId}

PARTIES
-------
Co-Venturer: Good Circles L3C, a Wyoming Limited Liability Company (L3C)
  ("Platform")

Charitable Organization: ${input.nonprofitName}
  EIN: ${input.nonprofitEin}
  ("Charity")

CAMPAIGN DETAILS
----------------
Geographic Scope: ${input.states.join(', ')}
Start Date: ${input.startDate.toISOString().split('T')[0]}
End Date: ${endDateStr}
Donation Commitment: ${donationDesc}
Transfer Deadline: ${transferDue} (${input.transferDeadlineDays} days post-campaign)

TERMS AND CONDITIONS
--------------------
1. DONATION COMMITMENT. Platform agrees to remit to Charity the amounts
   described above, calculated on all qualifying transactions occurring within
   the geographic scope and campaign period defined herein.

2. TRANSFER OF FUNDS. Platform shall transfer all accrued charitable funds to
   Charity no later than ${input.transferDeadlineDays} days after campaign end. Transfers will
   be made via ACH or check payable to Charity.

3. INSPECTION OF BOOKS. Charity shall have the right, upon reasonable written
   notice of no less than five (5) business days, to inspect Platform's books,
   records, and accounts pertaining to this campaign, as required by applicable
   state charitable solicitation statutes.

4. ACCURATE ACCOUNTING. Platform shall maintain accurate records of: (a) gross
   sales attributable to this campaign by state; (b) total charitable amounts
   accrued; (c) dates and amounts of all transfers to Charity.

5. CHARITABLE SOLICITATION COMPLIANCE. Platform represents that it is registered
   or exempt from registration as a Commercial Co-Venturer in each state listed
   in this agreement, or will obtain such registration before solicitation begins.

6. DISCLOSURE TO CONSUMERS. Platform shall display the following disclosure text
   at or before the point of purchase in all applicable states:
   "${donationDesc} will be donated to ${input.nonprofitName} (EIN ${input.nonprofitEin})."

7. TERMINATION. Either party may terminate this agreement upon 30 days written
   notice. Upon termination, Platform shall remit all accrued charitable funds
   within ${input.transferDeadlineDays} days.

8. GOVERNING LAW. This agreement is governed by the laws of the State of
   Wyoming, without regard to conflict-of-law principles.

9. ENTIRE AGREEMENT. This document constitutes the entire agreement between the
   parties with respect to this campaign and supersedes all prior negotiations
   or understandings.

SIGNATURES
----------
Platform (Good Circles L3C): _________________________ Date: ___________

Charity (${input.nonprofitName}): _________________________ Date: ___________

---
This contract was auto-generated by Good Circles Compliance Engine.
SHA-256 hash stored for record immutability. Retain for minimum 7 years.
`;
}

export class CcvContractService {
  static async generateAndStore(campaignId: string): Promise<{ contentHash: string }> {
    const campaign = await prisma.ccvCampaign.findUnique({
      where: { id: campaignId },
      include: { nonprofit: { select: { orgName: true, ein: true } } },
    });
    if (!campaign) throw new Error(`Campaign ${campaignId} not found`);

    const input: ContractInput = {
      campaignId: campaign.id,
      campaignName: campaign.name,
      nonprofitName: campaign.nonprofit.orgName,
      nonprofitEin: campaign.nonprofit.ein,
      states: campaign.states,
      startDate: campaign.startDate,
      endDate: campaign.endDate,
      donationMechanism: campaign.donationMechanism,
      donationAmount: campaign.donationAmount ? Number(campaign.donationAmount) : null,
      donationPercentage: campaign.donationPercentage ? Number(campaign.donationPercentage) : null,
      transferDeadlineDays: campaign.transferDeadlineDays,
    };

    const contractText = generateContractText(input);
    const contentHash = createHash('sha256').update(contractText, 'utf8').digest('hex');

    await prisma.ccvContract.upsert({
      where: { campaignId },
      update: { contractText, contentHash, updatedAt: new Date() },
      create: { campaignId, contractText, contentHash },
    });

    return { contentHash };
  }

  static async getContract(campaignId: string) {
    return prisma.ccvContract.findUnique({ where: { campaignId } });
  }

  static async recordSignature(
    campaignId: string,
    party: 'platform' | 'nonprofit',
    signatureToken: string,
  ) {
    const now = new Date();
    const data =
      party === 'platform'
        ? { platformSignedAt: now, platformSignature: signatureToken }
        : { nonprofitSignedAt: now, nonprofitSignature: signatureToken };
    return prisma.ccvContract.update({ where: { campaignId }, data });
  }

  static verifyIntegrity(contractText: string, storedHash: string): boolean {
    const computed = createHash('sha256').update(contractText, 'utf8').digest('hex');
    return computed === storedHash;
  }
}
