import { Prisma, PrismaClient } from '@prisma/client';
import { prisma } from '../lib/prisma';
import { Decimal } from '@prisma/client/runtime/library';
import { WalletService } from './walletService';



export class ReferralService {
  /**
   * Seed the referral bonus tiers if they don't exist.
   */
  static async seedTiers() {
    const tiers = [
      { tierName: 'Activation', threshold: 7500, bonus: 500 },
      { tierName: 'Established', threshold: 25000, bonus: 1000 },
      { tierName: 'High Volume', threshold: 75000, bonus: 2500 },
      { tierName: 'Anchor Merchant', threshold: 150000, bonus: 5000 },
    ];

    for (const t of tiers) {
      const existing = await prisma.referralBonusTier.findFirst({
        where: { tierName: t.tierName }
      });

      if (!existing) {
        await prisma.referralBonusTier.create({
          data: {
            tierName: t.tierName,
            nonprofitFundingThreshold: new Decimal(t.threshold),
            bonusAmount: new Decimal(t.bonus)
          }
        });
      }
    }
  }

  /**
   * Generate or get a referral code for a nonprofit.
   */
  static async getReferralCode(nonprofitId: string): Promise<string> {
    const nonprofit = await prisma.nonprofit.findUnique({
      where: { id: nonprofitId }
    });

    if (!nonprofit) throw new Error('Nonprofit not found');

    if (nonprofit.referralCode) return nonprofit.referralCode;

    // Generate a unique code
    const code = `REF-${nonprofit.orgName.replace(/\s+/g, '-').toUpperCase()}-${Math.random().toString(36).substring(2, 7).toUpperCase()}`;
    
    await prisma.nonprofit.update({
      where: { id: nonprofitId },
      data: { referralCode: code }
    });

    return code;
  }

  /**
   * Link a merchant to a nonprofit via referral code.
   */
  static async linkMerchant(merchantId: string, referralCode: string) {
    const nonprofit = await prisma.nonprofit.findUnique({
      where: { referralCode }
    });

    if (!nonprofit) return null;

    return prisma.merchantReferral.create({
      data: {
        referringNonprofitId: nonprofit.id,
        merchantId,
        referralCodeUsed: referralCode
      }
    });
  }

  /**
   * Check and process referral bonuses for a merchant.
   * This should be called after a transaction is processed or by a scheduled job.
   */
  static async checkReferralBonuses(merchantId: string, tx?: Prisma.TransactionClient) {
    const client = tx || prisma;

    // 1. Check if merchant was referred
    const referral = await client.merchantReferral.findUnique({
      where: { merchantId },
      include: { 
        payouts: true,
        referringNonprofit: { include: { user: true } }
      }
    });

    if (!referral || !referral.is_active) return;

    // 2. Calculate cumulative nonprofit funding generated by this merchant
    const transactions = await client.transaction.findMany({
      where: { merchantId }
    });

    const totalFunding = transactions.reduce((sum: Decimal, t: any) => sum.add(new Decimal(t.nonprofitShare)), new Decimal(0));
    const totalPlatformFees = transactions.reduce((sum: Decimal, t: any) => sum.add(new Decimal(t.platformFee)), new Decimal(0));

    // 3. Get all tiers
    const allTiers = await client.referralBonusTier.findMany({
      orderBy: { nonprofitFundingThreshold: 'asc' }
    });

    // 4. Identify which tiers have been reached but not paid
    const paidTierIds = referral.payouts.map((p: any) => p.tierId);
    const totalPaidBonuses = referral.payouts.reduce((sum: Decimal, p: any) => sum.add(new Decimal(p.amount)), new Decimal(0));

    let currentCumulativePayout = totalPaidBonuses;

    for (const tier of allTiers) {
      if (totalFunding.greaterThanOrEqualTo(tier.nonprofitFundingThreshold)) {
        if (!paidTierIds.includes(tier.id)) {
          // Invariant Check: Platform fees earned from the referred merchant exceed cumulative referral payouts
          const nextCumulativePayout = currentCumulativePayout.add(new Decimal(tier.bonusAmount));
          
          if (totalPlatformFees.lessThan(nextCumulativePayout)) {
            console.warn(`[ReferralService] INVARIANT VIOLATION: Platform fees (${totalPlatformFees}) are less than cumulative payout (${nextCumulativePayout}) for merchant ${merchantId}. Skipping payout for tier ${tier.tierName}.`);
            continue;
          }

          // Process payout
          const executePayout = async (txClient: Prisma.TransactionClient) => {
            // Create payout record
            await txClient.referralBonusPayout.create({
              data: {
                referralId: referral.id,
                tierId: tier.id,
                amount: tier.bonusAmount,
                nonprofitFundingAtPayout: totalFunding
              }
            });

            // Credit nonprofit's wallet
            await WalletService.fundWallet(
              referral.referringNonprofit.userId,
              Number(tier.bonusAmount),
              `Referral Bonus: ${tier.tierName} tier reached by ${referral.merchantId}`,
              txClient
            );
          };

          if (tx) {
            await executePayout(tx);
          } else {
            await prisma.$transaction(async (txClient: Prisma.TransactionClient) => {
              await executePayout(txClient);
            });
          }

          currentCumulativePayout = nextCumulativePayout;
          console.log(`[ReferralService] Payout of ${tier.bonusAmount} issued to nonprofit ${referral.referringNonprofitId} for merchant ${merchantId} reaching tier ${tier.tierName}`);
        }
      }
    }
  }

  /**
   * Daily job to process all active referrals.
   */
  static async processAllReferrals() {
    const activeReferrals = await prisma.merchantReferral.findMany({
      where: { is_active: true }
    });

    console.log(`[ReferralService] Processing ${activeReferrals.length} active referrals...`);

    for (const referral of activeReferrals) {
      try {
        await this.checkReferralBonuses(referral.merchantId);
      } catch (err) {
        console.error(`[ReferralService] Error processing referral for merchant ${referral.merchantId}:`, err);
      }
    }
  }

  /**
   * Get list of merchants referred by a nonprofit.
   */
  static async getNonprofitReferrals(nonprofitId: string) {
    const referrals = await prisma.merchantReferral.findMany({
      where: { referringNonprofitId: nonprofitId },
      include: {
        merchant: true,
        payouts: {
          include: { tier: true }
        }
      }
    });

    const allTiers = await prisma.referralBonusTier.findMany({
      orderBy: { nonprofitFundingThreshold: 'asc' }
    });

    return Promise.all(referrals.map(async (ref: any) => {
      const transactions = await prisma.transaction.findMany({
        where: { merchantId: ref.merchantId }
      });

      const totalFunding = transactions.reduce((sum: Decimal, t: any) => sum.add(new Decimal(t.nonprofitShare)), new Decimal(0));
      const totalBonuses = ref.payouts.reduce((sum: Decimal, p: any) => sum.add(new Decimal(p.amount)), new Decimal(0));

      const currentTier = ref.payouts.length > 0 
        ? ref.payouts.sort((a: any, b: any) => Number(b.tier.nonprofitFundingThreshold) - Number(a.tier.nonprofitFundingThreshold))[0].tier
        : null;

      const nextTier = allTiers.find((t: any) => Number(t.nonprofitFundingThreshold) > Number(totalFunding));

      return {
        id: ref.id,
        merchantId: ref.merchantId,
        businessName: ref.merchant.businessName,
        referredAt: ref.referredAt,
        totalFundingGenerated: totalFunding,
        totalBonusesEarned: totalBonuses,
        currentTier: currentTier ? currentTier.tierName : 'None',
        nextTier: nextTier ? {
          name: nextTier.tierName,
          threshold: nextTier.nonprofitFundingThreshold,
          progress: Number(totalFunding) / Number(nextTier.nonprofitFundingThreshold)
        } : null
      };
    }));
  }

  /**
   * Get detailed view for a specific referral.
   */
  static async getReferralDetail(referralId: string, nonprofitId: string) {
    const referral = await prisma.merchantReferral.findUnique({
      where: { id: referralId },
      include: {
        merchant: true,
        payouts: {
          include: { tier: true },
          orderBy: { paidAt: 'desc' }
        }
      }
    });

    if (!referral || referral.referringNonprofitId !== nonprofitId) {
      throw new Error('Referral not found');
    }

    const transactions = await prisma.transaction.findMany({
      where: { merchantId: referral.merchantId },
      orderBy: { createdAt: 'asc' }
    });

    const fundingTimeline = transactions.map((t: any) => ({
      date: t.createdAt,
      amount: t.nonprofitShare,
      cumulative: 0 // Will calculate below
    }));

    let runningTotal = new Decimal(0);
    fundingTimeline.forEach((item: any) => {
      runningTotal = runningTotal.add(new Decimal(item.amount));
      item.cumulative = runningTotal;
    });

    return {
      referral,
      fundingTimeline,
      totalFunding: runningTotal,
      payoutHistory: referral.payouts
    };
  }

  /**
   * Admin summary of referral bonuses.
   */
  static async getAdminReferralSummary() {
    const payouts = await prisma.referralBonusPayout.findMany({
      include: {
        referral: {
          include: {
            merchant: true,
            referringNonprofit: true
          }
        }
      }
    });

    const totalBonusesPaid = payouts.reduce((sum: Decimal, p: any) => sum.add(new Decimal(p.amount)), new Decimal(0));

    // Calculate total platform fees from all referred merchants
    const referredMerchantIds = await prisma.merchantReferral.findMany({
      select: { merchantId: true }
    }).then(refs => refs.map(r => r.merchantId));

    const transactions = await prisma.transaction.findMany({
      where: { merchantId: { in: referredMerchantIds } }
    });

    const totalPlatformFees = transactions.reduce((sum: Decimal, t: any) => sum.add(new Decimal(t.platformFee)), new Decimal(0));

    // Top recruiting nonprofits
    const nonprofits = await prisma.nonprofit.findMany({
      include: {
        referrals: true
      }
    });

    const topRecruiters = nonprofits
      .map((n: any) => ({
        id: n.id,
        orgName: n.orgName,
        referralCount: n.referrals.length
      }))
      .sort((a, b) => b.referralCount - a.referralCount)
      .slice(0, 5);

    return {
      totalBonusesPaid,
      totalPlatformFeesEarned: totalPlatformFees,
      netPlatformPosition: totalPlatformFees.sub(totalBonusesPaid),
      topRecruiters
    };
  }
}
